databases:
  - name: reedsy_challenge_backend
    plan: free
    databaseName: reedsy_challenge_backend
    user: reedsy_challenge_backend

services:
  - type: web
    plan: free
    name: reedsy-challenge-backend
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reedsy_challenge_backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
